--=============================
-- 1. Création de la Base de Données Oracle
--=============================

-- Création de l'utilisateur EntrepriseDB avec sys connecté à freepdb1
CREATE USER ENTREPRISEDB IDENTIFIED BY mdpentreprise;
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO ENTREPRISEDB;

SELECT USERNAME, DEFAULT_TABLESPACE FROM DBA_USERS;
COMMIT;

-- Création des tables avec la connexion de EntrepriseDB
ALTER SESSION SET CURRENT_SCHEMA = ENTREPRISEDB;

CREATE TABLE DEPARTEMENTS (
  DEP_ID NUMBER(5) PRIMARY KEY,
  NOM VARCHAR2(30) NOT NULL,
  LOCALISATION VARCHAR2(30),
  BUDGET  NUMBER(12,2)
);

CREATE TABLE EMPLOYES (
  EMP_ID NUMBER(6) PRIMARY KEY,
  NOM VARCHAR2(20) NOT NULL,
  PRENOM VARCHAR2(20) NOT NULL,
  POSTE VARCHAR2(25),
  SALAIRE NUMBER(10,2),
  DATE_EMBAUCHE DATE,
  DEP_ID NUMBER(5),
  CONSTRAINT fk_dep FOREIGN KEY (DEP_ID) REFERENCES DEPARTEMENTS(DEP_ID)
);

CREATE TABLE PROJETS (
  PROJ_ID    NUMBER(5)    PRIMARY KEY,
  NOM_PROJET VARCHAR2(40) NOT NULL,
  DATE_DEBUT DATE,
  DATE_FIN   DATE,
  STATUT     VARCHAR2(12) CHECK (STATUT IN ('EN_COURS','TERMINE','EN_ATTENTE')),
  DEP_ID     NUMBER(5),
  CONSTRAINT fk_proj_dep FOREIGN KEY (DEP_ID) REFERENCES DEPARTEMENTS(DEP_ID)
);

-- Insertion des données de test
INSERT INTO DEPARTEMENTS VALUES (1, 'Informatique', 'Montréal', 500000);
INSERT INTO DEPARTEMENTS VALUES (2, 'Ressources Humaines', 'Québec', 300000);
INSERT INTO DEPARTEMENTS VALUES (3, 'Finance', 'Toronto', 750000);
INSERT INTO DEPARTEMENTS VALUES (4, 'Marketing', 'Ottawa', 400000);

INSERT INTO EMPLOYES VALUES (101, 'Tremblay', 'Alice','Développeur', 72000, DATE '2021-03-15',1);
INSERT INTO EMPLOYES VALUES (102, 'Gagnon', 'Marc','Analyste RH', 58000, DATE '2019-07-01', 2);
INSERT INTO EMPLOYES VALUES (103, 'Leblanc', 'Sophie','Comptable', 65000, DATE '2020-11-20', 3);
INSERT INTO EMPLOYES VALUES (104, 'Roy','David', 'Chef Marketing', 70000 ,DATE '2022-01-10', 4);

INSERT INTO PROJETS VALUES (1, 'Refonte Site Web', DATE '2024-01-01', DATE '2024-06-30', 'TERMINE', 1);
INSERT INTO PROJETS VALUES (2, 'Audit RH 2025', DATE '2025-02-01', DATE '2025-05-31', 'EN_COURS', 2);
INSERT INTO PROJETS VALUES (3, 'Système Comptable v2', DATE '2025-03-15', DATE '2025-12-01', 'EN_COURS', 3);
INSERT INTO PROJETS VALUES (4, 'Campagne Printemps', DATE '2025-04-01', DATE '2025-04-30', 'EN_ATTENTE', 4);

COMMIT;
