--=============================
-- 2. Gestion des Rôles et Profils
--=============================

-- Création de rôles en tant que sys connecté à freepdb1
CREATE ROLE GESTIONNAIRE_PROJET;
CREATE ROLE GESTIONNAIRE_DEPARTEMENT;
CREATE ROLE ADMINISTRATEUR_DB;

-- Association des privilèges aux rôles
GRANT SELECT, INSERT, UPDATE, DELETE ON ENTREPRISEDB.PROJETS TO GESTIONNAIRE_PROJET;
GRANT SELECT ON ENTREPRISEDB.EMPLOYES TO GESTIONNAIRE_PROJET;
GRANT SELECT ON ENTREPRISEDB.DEPARTEMENTS TO GESTIONNAIRE_PROJET;

GRANT SELECT, INSERT, UPDATE, DELETE ON ENTREPRISEDB.DEPARTEMENTS TO GESTIONNAIRE_DEPARTEMENT;
GRANT SELECT, INSERT, UPDATE, DELETE ON ENTREPRISEDB.EMPLOYES TO GESTIONNAIRE_DEPARTEMENT;
GRANT SELECT ON ENTREPRISEDB.PROJETS TO GESTIONNAIRE_DEPARTEMENT;

GRANT SELECT ANY TABLE TO ADMINISTRATEUR_DB;
GRANT INSERT ANY TABLE TO ADMINISTRATEUR_DB;
GRANT UPDATE ANY TABLE TO ADMINISTRATEUR_DB;
GRANT DELETE ANY TABLE TO ADMINISTRATEUR_DB;
GRANT CREATE USER TO ADMINISTRATEUR_DB;
GRANT ALTER USER TO ADMINISTRATEUR_DB;
GRANT DROP USER TO ADMINISTRATEUR_DB;
GRANT CREATE ANY TABLE TO ADMINISTRATEUR_DB;
GRANT DROP ANY TABLE TO ADMINISTRATEUR_DB; 

-- Création des utilisateurs
CREATE USER chef_projet IDENTIFIED BY pass123 DEFAULT TABLESPACE USERS QUOTA 10M ON USERS;
CREATE USER chef_dept IDENTIFIED BY pass123 DEFAULT TABLESPACE USERS QUOTA 10M ON USERS;
CREATE USER admin_sys IDENTIFIED BY pass123 DEFAULT TABLESPACE USERS QUOTA 10M ON USERS;

GRANT CONNECT TO chef_projet;
GRANT CONNECT TO chef_dept;
GRANT CONNECT TO admin_sys;

GRANT GESTIONNAIRE_PROJET TO chef_projet;
GRANT GESTIONNAIRE_DEPARTEMENT TO chef_dept;
GRANT ADMINISTRATEUR_DB TO admin_sys;

-- Création du profil PROFIL_LIMIT_EMPLOYES
CREATE PROFILE PROFIL_LIMIT_EMPLOYES LIMIT
  SESSIONS_PER_USER 3  
  CPU_PER_SESSION 10000  
  CPU_PER_CALL 1000   
  CONNECT_TIME 60   
  IDLE_TIME 15 
  FAILED_LOGIN_ATTEMPTS 3 
  PASSWORD_LOCK_TIME 1/24   
  PASSWORD_LIFE_TIME 90    
  PASSWORD_REUSE_TIME 365   
  PASSWORD_REUSE_MAX 5   
  PASSWORD_GRACE_TIME 7;

ALTER USER chef_projet PROFILE PROFIL_LIMIT_EMPLOYES;
ALTER USER chef_dept PROFILE PROFIL_LIMIT_EMPLOYES;
