--=============================
-- 3. Audit
--=============================

-- Audit des connexions
CREATE AUDIT POLICY CONNEXIONS_AUDIT_POLICY
    ACTIONS LOGON;
AUDIT POLICY CONNEXIONS_AUDIT_POLICY;

-- Audit des modifications sur EMPLOYES
CREATE AUDIT POLICY EMPLOYES_AUDIT_POLICY
    ACTIONS INSERT ON ENTREPRISEDB.EMPLOYES,
        UPDATE ON ENTREPRISEDB.EMPLOYES,
        DELETE ON ENTREPRISEDB.EMPLOYES;
AUDIT POLICY EMPLOYES_AUDIT_POLICY;

-- Audit des modifications sur PROJETS
CREATE AUDIT POLICY PROJETS_AUDIT_POLICY
    ACTIONS INSERT ON ENTREPRISEDB.PROJETS,
        UPDATE ON ENTREPRISEDB.PROJETS,
        DELETE ON ENTREPRISEDB.PROJETS;
AUDIT POLICY PROJETS_AUDIT_POLICY;

-- Vérifications des policies actives
SELECT POLICY_NAME, ENTITY_NAME, SUCCESS, FAILURE
FROM AUDIT_UNIFIED_ENABLED_POLICIES;

-- Consultation des logs de connexion
SELECT DBUSERNAME, ACTION_NAME, EVENT_TIMESTAMP, RETURN_CODE
FROM UNIFIED_AUDIT_TRAIL
WHERE ACTION_NAME = 'LOGON'
ORDER BY EVENT_TIMESTAMP DESC;
